---
- name: Converge
  hosts: all
  tasks:
    - name: Print OS
      ansible.builtin.debug:
        msg: "Ansible OS Famaly: {{ ansible_os_family }}"

    - name: "Include igr33k.setup_woring_environment"
      ansible.builtin.include_role:
        name: "igr33k.setup_woring_environment"
      vars:
        user_name: hacker
        user_pass: changeme